"""central de notificacoes no app

Revision ID: 74b0d8176769
Revises: d4e5f6a7b8c9
Create Date: 2026-09-04 16:45:00.364020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74b0d8176769'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('chave', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('nivel', sa.String(length=10), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('lida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolvida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'chave', name='uq_notificacao_usuario_chave')
    )
    with op.batch_alter_table('notificacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificacao_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificacao_usuario_id'))

    op.drop_table('notificacao')
    # ### end Alembic commands ###
