"""esquema inicial

Revision ID: bc8b90ab66dd
Revises: 
Create Date: 2026-08-29 23:43:41.036383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc8b90ab66dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('moeda', sa.String(length=3), nullable=False),
    sa.Column('orcamento_mensal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('orcamento_diario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)

    op.create_table('categoria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('cor', sa.String(length=9), nullable=False),
    sa.Column('icone', sa.String(length=60), nullable=False),
    sa.Column('pai_id', sa.UUID(), nullable=True),
    sa.Column('orcamento_mensal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('arquivada', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pai_id'], ['categoria.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categoria_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('sessao_compra',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('local', sa.String(length=120), nullable=True),
    sa.Column('orcamento', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('aberta_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fechada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_carrinho', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_pago', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('motivo_divergencia', sa.String(length=200), nullable=True),
    sa.Column('lancamento_id', sa.UUID(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessao_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessao_compra_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('conta_agendada',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('valor_estimado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('dia_vencimento', sa.Integer(), nullable=False),
    sa.Column('recorrencia', sa.String(length=10), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('lembrete_dias', sa.Integer(), nullable=False),
    sa.Column('mes_referencia', sa.Integer(), nullable=True),
    sa.Column('ano_referencia', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conta_agendada', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conta_agendada_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('item_compra',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sessao_id', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('removido', sa.Boolean(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessao_compra.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_compra_sessao_id'), ['sessao_id'], unique=False)

    op.create_table('lancamento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=12), nullable=True),
    sa.Column('sessao_id', sa.UUID(), nullable=True),
    sa.Column('conta_id', sa.UUID(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lancamento', schema=None) as batch_op:
        batch_op.create_index('ix_lancamento_usuario_data', ['usuario_id', 'data'], unique=False)

    op.create_table('preco_historico',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('descricao_normalizada', sa.String(length=200), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('sessao_id', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessao_compra.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('preco_historico', schema=None) as batch_op:
        batch_op.create_index('ix_preco_usuario_descricao', ['usuario_id', 'descricao_normalizada'], unique=False)

    op.create_table('anexo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lancamento_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('caminho', sa.String(length=300), nullable=False),
    sa.Column('tipo_mime', sa.String(length=80), nullable=False),
    sa.Column('tamanho', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamento.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anexo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anexo_lancamento_id'), ['lancamento_id'], unique=False)

    op.create_table('ocorrencia_conta',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=False),
    sa.Column('competencia', sa.String(length=7), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('valor_real', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('lancamento_id', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['conta_agendada.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamento.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conta_id', 'competencia', 'vencimento', name='uq_ocorrencia_conta_competencia')
    )
    with op.batch_alter_table('ocorrencia_conta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocorrencia_conta_conta_id'), ['conta_id'], unique=False)

    # FKs circulares (lancamento <-> sessao_compra) criadas por ALTER depois das tabelas.
    op.create_foreign_key('fk_sessao_compra_lancamento_id', 'sessao_compra', 'lancamento', ['lancamento_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_lancamento_sessao_id', 'lancamento', 'sessao_compra', ['sessao_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_lancamento_conta_id', 'lancamento', 'conta_agendada', ['conta_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_lancamento_conta_id', 'lancamento', type_='foreignkey')
    op.drop_constraint('fk_lancamento_sessao_id', 'lancamento', type_='foreignkey')
    op.drop_constraint('fk_sessao_compra_lancamento_id', 'sessao_compra', type_='foreignkey')
    with op.batch_alter_table('ocorrencia_conta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocorrencia_conta_conta_id'))

    op.drop_table('ocorrencia_conta')
    with op.batch_alter_table('anexo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anexo_lancamento_id'))

    op.drop_table('anexo')
    with op.batch_alter_table('preco_historico', schema=None) as batch_op:
        batch_op.drop_index('ix_preco_usuario_descricao')

    op.drop_table('preco_historico')
    with op.batch_alter_table('lancamento', schema=None) as batch_op:
        batch_op.drop_index('ix_lancamento_usuario_data')

    op.drop_table('lancamento')
    with op.batch_alter_table('item_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_compra_sessao_id'))

    op.drop_table('item_compra')
    with op.batch_alter_table('conta_agendada', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conta_agendada_usuario_id'))

    op.drop_table('conta_agendada')
    with op.batch_alter_table('sessao_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessao_compra_usuario_id'))

    op.drop_table('sessao_compra')
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categoria_usuario_id'))

    op.drop_table('categoria')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    # ### end Alembic commands ###
